### ISSUE TITLE
Reminder : remove SameSiteNoneMiddleware when Django 3.1 is out

### ISSUE THREAD

**Issue by madmatah** [openfun/ashley#41]
The `SameSiteNoneMiddleware` is a temporary fix  before the public release of Django 3.1.

### TODO when Django 3.1 is released : 

 - [ ] Upgrade Django dependency and fix potential issues with Django 3.1
 - [ ] Set `CSRF_COOKIE_SAMESITE = "none"` in sandbox settings
 - [ ] Set  `SESSION_COOKIE_SAMESITE = "none"` in sandbox settings
